angular.module('polymerTesterApp',[]).controller('polymerTesterController',function(){
	var ptc=this;
	ptc.test=function(){alert("yo")};
	ptc.hi="yo";
	ptc.ironlist=[
		{toLearn: 'iron-a11y-announcer',done:false, href:'downloaded-polymer/iron-a11y-announcer/'},
		{toLearn: 'iron-a11y-keys',done:false, href:'downloaded-polymer/iron-a11y-keys/'},
		{toLearn: 'iron-a11y-keys-behavior',done:false, href:'downloaded-polymer/iron-a11y-keys-behavior/'},
		{toLearn: 'iron-ajax',done:false, href:'downloaded-polymer/iron-ajax/'},
		{toLearn: 'iron-autogrow-textarea',done:false, href:'downloaded-polymer/iron-autogrow-textarea/'},
		{toLearn: 'iron-behaviors',done:false, href:'downloaded-polymer/iron-behaviors/'},
		{toLearn: 'iron-checked-element-behavior',done:false, href:'downloaded-polymer/iron-checked-element-behavior/'},
		{toLearn: 'iron-collapse',done:false, href:'downloaded-polymer/iron-collapse/'},
		{toLearn: 'iron-component-page',done:false, href:'downloaded-polymer/iron-component-page/'},
		{toLearn: 'iron-doc-viewer',done:false, href:'downloaded-polymer/iron-doc-viewer/'},
		{toLearn: 'iron-dropdown',done:false, href:'downloaded-polymer/iron-dropdown/'},
		{toLearn: 'iron-elements',done:false, href:'downloaded-polymer/iron-elements/'},
		{toLearn: 'iron-fit-behavior',done:false, href:'downloaded-polymer/iron-fit-behavior/'},
		{toLearn: 'iron-flex-layout',done:false, href:'downloaded-polymer/iron-flex-layout/'},
		{toLearn: 'iron-form',done:false, href:'downloaded-polymer/iron-form/'},
		{toLearn: 'iron-form-element-behavior',done:false, href:'downloaded-polymer/iron-form-element-behavior/'},
		{toLearn: 'iron-icon',done:false, href:'downloaded-polymer/iron-icon/'},
		{toLearn: 'iron-icons',done:false, href:'downloaded-polymer/iron-icons/'},
		{toLearn: 'iron-iconset',done:false, href:'downloaded-polymer/iron-iconset/'},
		{toLearn: 'iron-iconset-svg',done:false, href:'downloaded-polymer/iron-iconset-svg/'},
		{toLearn: 'iron-image',done:false, href:'downloaded-polymer/iron-image/'},
		{toLearn: 'iron-input',done:false, href:'downloaded-polymer/iron-input/'},
		{toLearn: 'iron-jsonp-libray',done:false, href:'downloaded-polymer/iron-jsonp-libray/'},
		{toLearn: 'iron-list',done:false, href:'downloaded-polymer/iron-list/'},
		{toLearn: 'iron-localstorage',done:false, href:'downloaded-polymer/iron-localstorage/'},
		{toLearn: 'iron-media-query',done:false, href:'downloaded-polymer/iron-media-query/'},
		{toLearn: 'iron-menu-behavior',done:false, href:'downloaded-polymer/iron-menu-behavior/'},
		{toLearn: 'iron-meta',done:false, href:'downloaded-polymer/iron-meta/'},
		{toLearn: 'iron-overlay-behavior',done:false, href:'downloaded-polymer/iron-overlay-behavior/'},
		{toLearn: 'iron-pages',done:false, href:'downloaded-polymer/iron-pages/'},
		{toLearn: 'iron-range-behavior',done:false, href:'downloaded-polymer/iron-range-behavior/'},
		{toLearn: 'iron-resizable-behavior',done:false, href:'downloaded-polymer/iron-resizable-behavior/'},
		{toLearn: 'iron-selector',done:false, href:'downloaded-polymer/iron-selector/'},
		{toLearn: 'iron-signals',done:false, href:'downloaded-polymer/iron-signals/'},
		{toLearn: 'iron-test-helpers',done:false, href:'downloaded-polymer/iron-test-helpers/'},
		{toLearn: 'iron-validatable-behavior',done:false, href:'downloaded-polymer/iron-validatable-behavior/'},
		{toLearn: 'iron-validator-behavior',done:false, href:'downloaded-polymer/iron-validator-behavior/'},
	];
	ptc.paperlist=[
		{toLearn: 'paper-badge',done:false, href:'downloaded-polymer/paper-badge/'},
		{toLearn: 'paper-behaviors',done:false, href:'downloaded-polymer/paper-behaviors/'},
		{toLearn: 'paper-button',done:false, href:'downloaded-polymer/paper-button/'},
		{toLearn: 'paper-card',done:false, href:'downloaded-polymer/paper-card/'},
		{toLearn: 'paper-checkbox',done:false, href:'downloaded-polymer/paper-checkbox/'},
		{toLearn: 'paper-dialog',done:false, href:'downloaded-polymer/paper-dialog/'},
		{toLearn: 'paper-dialog-behavior',done:false, href:'downloaded-polymer/paper-dialog-behavior/'},
		{toLearn: 'paper-dialog-scrollable',done:false, href:'downloaded-polymer/paper-dialog-scrollable/'},
		{toLearn: 'paper-drawer-panel',done:false, href:'downloaded-polymer/paper-drawer-panel/'},
		{toLearn: 'paper-dropdown-menu',done:false, href:'downloaded-polymer/paper-dropdown-menu/'},
		{toLearn: 'paper-elements',done:false, href:'downloaded-polymer/paper-elements/'},
		{toLearn: 'paper-fab',done:false, href:'downloaded-polymer/paper-fab/'},
		{toLearn: 'paper-header-panel',done:false, href:'downloaded-polymer/paper-header-panel/'},
		{toLearn: 'paper-icon-button',done:false, href:'downloaded-polymer/paper-icon-button/'},
		{toLearn: 'paper-input',done:false, href:'downloaded-polymer/paper-input/'},
		{toLearn: 'paper-item',done:false, href:'downloaded-polymer/paper-item/'},
		{toLearn: 'paper-material',done:false, href:'downloaded-polymer/paper-material/'},
		{toLearn: 'paper-menu',done:false, href:'downloaded-polymer/paper-menu/'},
		{toLearn: 'paper-menu-button',done:false, href:'downloaded-polymer/paper-menu-button/'},
		{toLearn: 'paper-progress',done:false, href:'downloaded-polymer/paper-progress/'},
		{toLearn: 'paper-radio-button',done:false, href:'downloaded-polymer/paper-radio-button/'},
		{toLearn: 'paper-radio-group',done:false, href:'downloaded-polymer/paper-radio-group/'},
		{toLearn: 'paper-ripple',done:false, href:'downloaded-polymer/paper-ripple/'},
		{toLearn: 'paper-scroll-header-panel',done:false, href:'downloaded-polymer/paper-scroll-header-panel/'},
		{toLearn: 'paper-slider',done:false, href:'downloaded-polymer/paper-slider/'},
		{toLearn: 'paper-spinner',done:false, href:'downloaded-polymer/paper-spinner/'},
		{toLearn: 'paper-styles',done:false, href:'downloaded-polymer/paper-styles/'},
		{toLearn: 'paper-tabs',done:false, href:'downloaded-polymer/paper-tabs/'},
		{toLearn: 'paper-taost',done:false, href:'downloaded-polymer/paper-taost/'},
		{toLearn: 'paper-toggle-button',done:false, href:'downloaded-polymer/paper-toggle-button/'},
		{toLearn: 'paper-toolbar',done:false, href:'downloaded-polymer/paper-toolbar/'},
		{toLearn: 'paper-tooltip',done:false, href:'downloaded-polymer/paper-tooltip/'}
	];
	ptc.platinumlist=[
		{toLearn: 'platinum-bluetooth',done:false, href:'downloaded-polymer/platinum-bluetooth/'},
		{toLearn: 'platinum-elements',done:false, href:'downloaded-polymer/platinum-elements/'},
		{toLearn: 'platinum-https-redirect',done:false, href:'downloaded-polymer/platinum-https-redirect/'},
		{toLearn: 'platinum-push-messaging',done:false, href:'downloaded-polymer/platinum-push-messaging/'},
		{toLearn: 'platinum-sw',done:false, href:'downloaded-polymer/platinum-sw/'},
	];
	ptc.mislist=[
		{toLearn: 'lodash',done:false, href:'downloaded-polymer/lodash/'},
		{toLearn: 'marked',done:false, href:'downloaded-polymer/marked/'},
		{toLearn: 'marked-element',done:false, href:'downloaded-polymer/marked-element/'},
		{toLearn: 'mocha',done:false, href:'downloaded-polymer/mocha/'},
		{toLearn: 'neon-animation',done:false, href:'downloaded-polymer/neon-animation/'},
		{toLearn: 'neon-elements',done:false, href:'downloaded-polymer/neon-elements/'},
		{toLearn: 'page',done:false, href:'downloaded-polymer/page/'},
		{toLearn: '<hr>',done:false, href:'downloaded-polymer/<hr>/'},
		{toLearn: 'polymer',done:false, href:'downloaded-polymer/polymer/'},
		{toLearn: 'prism',done:false, href:'downloaded-polymer/prism/'},
		{toLearn: 'prism-element',done:false, href:'downloaded-polymer/prism-element/'},
		{toLearn: 'promise-polyfill',done:false, href:'downloaded-polymer/promise-polyfill/'},
		{toLearn: 'sinon-chai',done:false, href:'downloaded-polymer/sinon-chai/'},
		{toLearn: 'sinonjs',done:false, href:'downloaded-polymer/sinonjs/'},
		{toLearn: 'stacky',done:false, href:'downloaded-polymer/stacky/'},
		{toLearn: 'sw-toolbox',done:false, href:'downloaded-polymer/sw-toolbox/'},
		{toLearn: 'test-fixture',done:false, href:'downloaded-polymer/test-fixture/'},
		{toLearn: 'web-animation-js',done:false, href:'downloaded-polymer/web-animation-js/'},
		{toLearn: 'web-component-tester',done:false, href:'downloaded-polymer/web-component-tester/'},
		{toLearn: 'webcomponentjs',done:false, href:'downloaded-polymer/webcomponentjs/'},
	];
});